"""
Veridict Batch Evaluation Report Generator (CSV & PDF).

Generates downloadable evaluated CSV files and executive multi-row ReportLab PDF reports
for batch evaluation jobs using BaseBatchExporter strategy pattern.
"""

import csv
from io import BytesIO, StringIO
import os
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    Image as RLImage,
)

from app.schemas.batch_evaluation import BatchProgress, BatchItemEvaluationResult
from app.services.batch_exporter_base import BaseBatchExporter, BatchExporterFactory

LOGO_PATH = "c:/Users/abhik/Desktop/Veridict/frontend/src/assets/logo.png"


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for rendering running footers across pages."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()

        # Running Footer
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 36, 576, 36)

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(36, 24, "Generated by Veridict | Batch Evaluation Summary Report")
        self.drawRightString(576, 24, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


class CSVBatchExporter(BaseBatchExporter):
    """Exports evaluated batch results to CSV format."""

    def export(self, progress: BatchProgress) -> bytes:
        output = StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "ID",
            "Row Index",
            "Question",
            "AI Response",
            "Reference Answer",
            "Evidence Source",
            "Relevance (1-5)",
            "Accuracy (1-5)",
            "Hallucination (1-5)",
            "Completeness (1-5)",
            "Overall Score",
            "Verdict",
            "Reasoning",
        ])

        for item in progress.items:
            writer.writerow([
                item.id,
                item.row_index,
                item.question,
                item.ai_response,
                item.reference_answer or "",
                item.evidence_source,
                item.relevance_score,
                item.accuracy_score,
                item.hallucination_score if item.hallucination_score is not None else "N/A",
                item.completeness_score,
                item.overall_score,
                item.verdict,
                item.reasoning,
            ])

        csv_bytes = output.getvalue().encode("utf-8-sig")
        output.close()
        return csv_bytes


class PDFBatchExporter(BaseBatchExporter):
    """Exports evaluated batch results to executive PDF format."""

    def export(self, progress: BatchProgress) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=48,
            bottomMargin=42,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#0F172A"),
            alignment=1,
        )
        subtitle_style = ParagraphStyle(
            "ReportSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#F97316"),
            alignment=1,
        )
        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=6,
            spaceAfter=3,
        )
        body_style = ParagraphStyle(
            "BodyText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#334155"),
        )

        now = datetime.now()
        gen_time = now.strftime("%d %b %Y, %I:%M %p")

        story: list[Any] = []

        # 1. Header
        if os.path.exists(LOGO_PATH):
            logo_img = RLImage(LOGO_PATH, width=28, height=28)
            logo_text = Paragraph(
                "<font color='#F97316' size='16'><b>VERIDICT</b></font><br/>"
                "<font color='#64748B' size='7.5'>Batch Evaluation Engine</font>",
                styles["Normal"],
            )
            brand_box = Table([[logo_img, logo_text]], colWidths=[34, 236])
            brand_box.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
            logo_elem = brand_box
        else:
            logo_elem = Paragraph(
                "<font color='#F97316' size='16'><b>VERIDICT</b></font><br/>"
                "<font color='#64748B' size='7.5'>Batch Evaluation Engine</font>",
                styles["Normal"],
            )

        meta_info = Paragraph(
            f"<font color='#0F172A' size='8.5'><b>Batch ID:</b> {progress.batch_id}</font><br/>"
            f"<font color='#64748B' size='7.5'><b>Generated:</b> {gen_time}</font>",
            ParagraphStyle("RAlign", parent=styles["Normal"], alignment=2),
        )
        header_table = Table([[logo_elem, meta_info]], colWidths=[270, 270])
        header_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        story.append(header_table)
        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#F97316"), spaceAfter=10))

        # 2. Title
        story.append(Paragraph("Veridict Batch Evaluation Report", title_style))
        story.append(Paragraph(f"Dataset: {progress.filename} ({progress.total_rows} QA Pairs)", subtitle_style))
        story.append(Spacer(1, 10))

        # 3. Summary Metrics Box
        items = progress.items
        pass_count = sum(1 for i in items if i.verdict == "PASS")
        needs_imp_count = sum(1 for i in items if i.verdict == "NEEDS_IMPROVEMENT")
        fail_count = sum(1 for i in items if i.verdict == "FAIL" or i.status == "FAILED")
        avg_score = (sum(i.overall_score for i in items) / len(items)) if items else 0.0
        pass_rate = (pass_count / len(items) * 100) if items else 0.0

        metrics_data = [
            [
                Paragraph("<b>Total Processed</b>", body_style),
                Paragraph("<b>Average Score</b>", body_style),
                Paragraph("<b>Pass Rate</b>", body_style),
                Paragraph("<b>Pass / Imp / Fail</b>", body_style),
            ],
            [
                Paragraph(f"<font size='14'><b>{len(items)}</b></font>", body_style),
                Paragraph(f"<font size='14'><b>{avg_score:.2f} / 5.00</b></font>", body_style),
                Paragraph(f"<font size='14' color='#15803D'><b>{pass_rate:.1f}%</b></font>", body_style),
                Paragraph(f"<font size='12'><b>{pass_count} / {needs_imp_count} / {fail_count}</b></font>", body_style),
            ],
        ]
        metrics_table = Table(metrics_data, colWidths=[135, 135, 135, 135])
        metrics_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 7),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(metrics_table)
        story.append(Spacer(1, 10))

        # 4. Results Breakdown Table
        story.append(Paragraph("Dataset Items Evaluation Breakdown", heading_style))

        headers = [
            Paragraph("<b>ID</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Question</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Rel</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Acc</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Hal</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Comp</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Score</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
            Paragraph("<b>Verdict</b>", ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)),
        ]
        table_rows = [headers]

        for item in items:
            q_short = item.question[:45] + "..." if len(item.question) > 45 else item.question
            hal_str = f"{item.hallucination_score:.0f}" if item.hallucination_score is not None else "-"

            if item.verdict == "PASS":
                v_color = "#15803D"
            elif item.verdict == "NEEDS_IMPROVEMENT":
                v_color = "#B45309"
            else:
                v_color = "#B91C1C"

            v_html = f"<font color='{v_color}'><b>{item.verdict.replace('_', ' ')}</b></font>"

            table_rows.append([
                Paragraph(item.id, body_style),
                Paragraph(q_short, body_style),
                Paragraph(f"{item.relevance_score:.0f}", body_style),
                Paragraph(f"{item.accuracy_score:.0f}", body_style),
                Paragraph(hal_str, body_style),
                Paragraph(f"{item.completeness_score:.0f}", body_style),
                Paragraph(f"<b>{item.overall_score:.2f}</b>", body_style),
                Paragraph(v_html, body_style),
            ])

        results_table = Table(table_rows, colWidths=[45, 195, 35, 35, 35, 35, 45, 115])
        results_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ])
        )
        story.append(results_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes


# Register concrete exporters with factory
BatchExporterFactory.register("CSV", CSVBatchExporter)
BatchExporterFactory.register("PDF", PDFBatchExporter)


class BatchReportGenerator:
    """Convenience façade for generating CSV and PDF batch exports."""

    @staticmethod
    def generate_batch_csv(items: list[BatchItemEvaluationResult]) -> bytes:
        temp_progress = BatchProgress(
            batch_id="TEMP",
            filename="export.csv",
            file_type="CSV",
            total_rows=len(items),
            processed_rows=len(items),
            remaining_rows=0,
            current_batch=1,
            total_batches=1,
            items=items,
            status="COMPLETED",
        )
        exporter = BatchExporterFactory.get_exporter("CSV")
        return exporter.export(temp_progress)

    @staticmethod
    def generate_batch_pdf(progress: BatchProgress) -> bytes:
        exporter = BatchExporterFactory.get_exporter("PDF")
        return exporter.export(progress)
