"""
Veridict PDF Report Generator Service (v1.1 Polish).

Generates a polished, enterprise-grade single-page Executive Assessment Report
in PDF format using ReportLab.
"""

from io import BytesIO
import os
import secrets
import string
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
    Image as RLImage,
)

LOGO_PATH = "c:/Users/abhik/Desktop/Veridict/frontend/src/assets/logo.png"


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas for rendering page numbers ('Page X of Y')
    and running footers across all pages automatically.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()

        # Running Footer
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 36, 576, 36)

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(36, 24, "Generated by Veridict | Executive Assessment Report v1.1")
        self.drawRightString(576, 24, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


class PDFReportGenerator:
    """
    Enterprise Executive Assessment PDF Report Generator for Veridict.
    Produces a clean, single-page summary suitable for academic and client delivery.
    """

    def generate_report(self, evaluation_data: dict[str, Any]) -> bytes:
        """
        Generate a concise Executive Assessment Report PDF buffer.

        Args:
            evaluation_data: Dictionary matching EvaluationResponse schema.

        Returns:
            bytes: Binary PDF stream.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=48,  # Prevent header/logo clipping
            bottomMargin=42,
        )

        styles = getSampleStyleSheet()
        self._setup_custom_styles(styles)

        now = datetime.now()
        rand_suffix = "".join(secrets.choice(string.digits) for _ in range(6))
        eval_id = f"VRD-{now.strftime('%Y%m%d')}-{rand_suffix}"
        gen_time = now.strftime("%d %b %Y, %I:%M %p")

        story: list[Any] = []

        # 1. Header with Logo & Evaluation ID
        self._build_header(story, eval_id, gen_time, styles)

        # 2. Report Title & Topic
        self._build_title_and_topic(story, evaluation_data, styles)

        # 3. Section 1: Executive Summary
        self._build_executive_summary(story, evaluation_data, styles)

        # 4. Section 2: Evaluation Summary Table
        self._build_evaluation_table(story, evaluation_data, styles)

        # 5. Section 3 & 4: Key Strengths & Improvement Areas
        self._build_strengths_and_improvements(story, evaluation_data, styles)

        # 6. Section 5: Agent Executive Summary
        self._build_agent_summary(story, evaluation_data, styles)

        # 7. Section 6: Final Recommendation
        self._build_conclusion(story, evaluation_data, styles)

        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    def _setup_custom_styles(self, styles: Any) -> None:
        """Define custom paragraph styles for report formatting."""
        styles.add(
            ParagraphStyle(
                name="RightAlign",
                parent=styles["Normal"],
                alignment=2,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ReportTitle",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=18,
                leading=22,
                textColor=colors.HexColor("#0F172A"),
                alignment=1,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ReportSubTitle",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=9,
                leading=13,
                textColor=colors.HexColor("#F97316"),
                alignment=1,
            )
        )
        styles.add(
            ParagraphStyle(
                name="SectionHeading",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=11,
                leading=14,
                textColor=colors.HexColor("#0F172A"),
                spaceBefore=6,
                spaceAfter=3,
            )
        )
        styles.add(
            ParagraphStyle(
                name="BodyTextLight",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=12,
                textColor=colors.HexColor("#334155"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="MetaLabel",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                textColor=colors.HexColor("#64748B"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="BadgeStyle",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=12,
                alignment=2,
                rightIndent=8,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ScoreStyle",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=10,
                leading=16,
            )
        )
        styles.add(
            ParagraphStyle(
                name="TableHeader",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                textColor=colors.white,
            )
        )
        styles.add(
            ParagraphStyle(
                name="TableCell",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                textColor=colors.HexColor("#0F172A"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="TableCellBold",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                textColor=colors.HexColor("#0F172A"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="TableCellMuted",
                parent=styles["Normal"],
                fontName="Helvetica-Oblique",
                fontSize=8.5,
                textColor=colors.HexColor("#64748B"),
            )
        )

    def _build_header(
        self, story: list[Any], eval_id: str, gen_time: str, styles: Any
    ) -> None:
        if os.path.exists(LOGO_PATH):
            logo_img = RLImage(LOGO_PATH, width=28, height=28)
            logo_text = Paragraph(
                "<font color='#F97316' size='16'><b>VERIDICT</b></font><br/>"
                "<font color='#64748B' size='7.5'>AI Response Quality Evaluator</font>",
                styles["Normal"],
            )
            brand_box = Table([[logo_img, logo_text]], colWidths=[34, 236])
            brand_box.setStyle(
                TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ])
            )
            logo_element = brand_box
        else:
            logo_element = Paragraph(
                "<font color='#F97316' size='16'><b>VERIDICT</b></font><br/>"
                "<font color='#64748B' size='7.5'>AI Response Quality Evaluator</font>",
                styles["Normal"],
            )

        meta_info = Paragraph(
            f"<font color='#0F172A' size='8.5'><b>Evaluation ID:</b> {eval_id}</font><br/>"
            f"<font color='#64748B' size='7.5'><b>Generated:</b> {gen_time}</font>",
            styles["RightAlign"],
        )
        header_table = Table([[logo_element, meta_info]], colWidths=[270, 270])
        header_table.setStyle(
            TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ])
        )
        story.append(header_table)
        story.append(Spacer(1, 6))
        story.append(
            HRFlowable(
                width="100%",
                thickness=1.5,
                color=colors.HexColor("#F97316"),
                spaceAfter=10,
            )
        )

    def _build_title_and_topic(
        self, story: list[Any], evaluation_data: dict[str, Any], styles: Any
    ) -> None:
        story.append(
            Paragraph("Veridict Executive Assessment Report", styles["ReportTitle"])
        )
        story.append(
            Paragraph(
                "AI Response Quality Evaluation",
                styles["ReportSubTitle"],
            )
        )

        question = evaluation_data.get("question", "").strip()
        if question:
            clean_question = " ".join(question.split())
            if len(clean_question) > 130:
                words = clean_question[:130].rsplit(" ", 1)[0] + "..."
            else:
                words = clean_question
            story.append(Spacer(1, 3))
            story.append(
                Paragraph(
                    f"<font color='#64748B' size='8'><b>Evaluation Topic:</b> <i>{words}</i></font>",
                    styles["ReportSubTitle"],
                )
            )

        story.append(Spacer(1, 10))

    def _build_executive_summary(
        self, story: list[Any], evaluation_data: dict[str, Any], styles: Any
    ) -> None:
        verdict_eval = evaluation_data.get("verdict_evaluation")
        story.append(Paragraph("1. Executive Summary", styles["SectionHeading"]))

        verdict_str = verdict_eval.get("verdict", "PASS") if verdict_eval else "PASS"
        overall_score = (
            verdict_eval.get("overall_score", 5.0) if verdict_eval else 5.0
        )
        verdict_reasoning = (
            verdict_eval.get("reasoning", "")
            if verdict_eval
            else "The evaluation demonstrates strong overall model performance."
        )

        sentences = [s.strip() for s in verdict_reasoning.split(".") if s.strip()]
        short_summary = ". ".join(sentences[:3]) + "." if sentences else verdict_reasoning

        _, fg_color, _ = self._get_badge_colors(verdict_str)

        score_stars = self._get_star_rating(overall_score)
        # Position stars above score with distinct line height to prevent overlap
        score_text = Paragraph(
            f"<font color='#F97316' size='10'><b>{score_stars}</b></font><br/>"
            f"<font color='#0F172A' size='22'><b>{overall_score:.2f}</b></font>"
            f"<font color='#64748B' size='10'> / 5.00</font>",
            styles["ScoreStyle"],
        )
        badge_text = Paragraph(
            f"<font color='{fg_color}' size='12'><b>{verdict_str.replace('_', ' ')}</b></font>",
            styles["BadgeStyle"],
        )

        summary_box = Table(
            [
                [
                    Paragraph("<b>Overall Score</b>", styles["MetaLabel"]),
                    Paragraph("<b>Verdict Status</b>", styles["MetaLabel"]),
                ],
                [score_text, badge_text],
                [
                    Paragraph(
                        f"<b>Assessment Summary:</b> {short_summary}",
                        styles["BodyTextLight"],
                    ),
                    "",
                ],
            ],
            colWidths=[270, 270],
        )
        summary_box.setStyle(
            TableStyle([
                ("SPAN", (0, 2), (1, 2)),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#E2E8F0")),
                ("PADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (1, 0), (1, 1), 16),  # Extra right padding for verdict badge
                ("TOPPADDING", (0, 2), (-1, 2), 10),    # Extra spacing above Assessment Summary
                ("BOTTOMPADDING", (0, 2), (-1, 2), 8),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(summary_box)
        story.append(Spacer(1, 8))

    def _build_evaluation_table(
        self, story: list[Any], evaluation_data: dict[str, Any], styles: Any
    ) -> None:
        story.append(Paragraph("2. Evaluation Summary", styles["SectionHeading"]))

        table_data = [
            [
                Paragraph("<b>Dimension</b>", styles["TableHeader"]),
                Paragraph("<b>Score</b>", styles["TableHeader"]),
                Paragraph("<b>Status</b>", styles["TableHeader"]),
            ]
        ]

        relevance_eval = evaluation_data.get("relevance_evaluation")
        accuracy_eval = evaluation_data.get("accuracy_evaluation")
        hallucination_eval = evaluation_data.get("hallucination_evaluation")
        completeness_eval = evaluation_data.get("completeness_evaluation")

        if relevance_eval:
            rel_score = relevance_eval.get("relevance_score", 5)
            table_data.append([
                Paragraph("Relevance", styles["TableCellBold"]),
                Paragraph(f"{rel_score} / 5", styles["TableCell"]),
                Paragraph(self._get_relevance_badge(rel_score), styles["TableCell"]),
            ])

        if accuracy_eval:
            acc_score = accuracy_eval.get("accuracy_score", 5)
            table_data.append([
                Paragraph("Accuracy", styles["TableCellBold"]),
                Paragraph(f"{acc_score} / 5", styles["TableCell"]),
                Paragraph(self._get_accuracy_badge(acc_score), styles["TableCell"]),
            ])

        if hallucination_eval:
            if hallucination_eval.get("status") == "INSUFFICIENT_EVIDENCE":
                table_data.append([
                    Paragraph("Hallucination", styles["TableCellBold"]),
                    Paragraph("Not Evaluated", styles["TableCellMuted"]),
                    Paragraph("<font color='#64748B'><b>● Insufficient Evidence</b></font>", styles["TableCellMuted"]),
                ])
            else:
                hal_score = hallucination_eval.get("hallucination_score", 5)
                table_data.append([
                    Paragraph("Hallucination", styles["TableCellBold"]),
                    Paragraph(f"{hal_score} / 5", styles["TableCell"]),
                    Paragraph(
                        self._get_hallucination_badge(hal_score), styles["TableCell"]
                    ),
                ])

        if completeness_eval:
            comp_score = completeness_eval.get("completeness_score", 5)
            table_data.append([
                Paragraph("Completeness", styles["TableCellBold"]),
                Paragraph(f"{comp_score} / 5", styles["TableCell"]),
                Paragraph(
                    self._get_completeness_badge(comp_score), styles["TableCell"]
                ),
            ])

        overview_table = Table(table_data, colWidths=[180, 120, 240])
        overview_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#F8FAFC")],
                ),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ])
        )
        story.append(overview_table)
        story.append(Spacer(1, 8))

    def _extract_strengths(self, evaluation_data: dict[str, Any]) -> str:
        relevance_eval = evaluation_data.get("relevance_evaluation")
        accuracy_eval = evaluation_data.get("accuracy_evaluation")
        hallucination_eval = evaluation_data.get("hallucination_evaluation")
        completeness_eval = evaluation_data.get("completeness_evaluation")

        strengths = []
        if relevance_eval and relevance_eval.get("relevance_score", 0) >= 4:
            strengths.append("<font color='#15803D'><b>✓</b></font> Highly relevant intent alignment")
        if accuracy_eval and accuracy_eval.get("accuracy_score", 0) >= 4:
            strengths.append("<font color='#15803D'><b>✓</b></font> Factually accurate core content")
        if hallucination_eval and hallucination_eval.get("hallucination_score", 0) >= 4:
            strengths.append("<font color='#15803D'><b>✓</b></font> Fully grounded in context")
        if completeness_eval and completeness_eval.get("completeness_score", 0) >= 4:
            strengths.append("<font color='#15803D'><b>✓</b></font> Complete requirement coverage")

        if not strengths:
            strengths.append("• Basic response structure maintained.")

        return "<br/>".join(strengths[:5])

    def _extract_improvements(self, evaluation_data: dict[str, Any], verdict_str: str) -> str:
        if verdict_str == "PASS":
            return "<font color='#15803D'><b>✓ No significant quality issues detected.</b></font>"

        relevance_eval = evaluation_data.get("relevance_evaluation")
        accuracy_eval = evaluation_data.get("accuracy_evaluation")
        completeness_eval = evaluation_data.get("completeness_evaluation")

        improvements = []
        if completeness_eval and completeness_eval.get("missing_aspects"):
            for aspect in completeness_eval["missing_aspects"][:2]:
                improvements.append(f"<font color='#B91C1C'>•</font> Missing aspect: {aspect}")
        if relevance_eval and relevance_eval.get("relevance_score", 5) < 4:
            improvements.append("<font color='#B91C1C'>•</font> Refine focus to prevent query drift")
        if accuracy_eval and accuracy_eval.get("accuracy_score", 5) < 4:
            improvements.append("<font color='#B91C1C'>•</font> Correct factual inaccuracies")

        if not improvements:
            improvements.append("<font color='#64748B'>• Minor phrasing adjustments recommended.</font>")

        return "<br/>".join(improvements[:4])

    def _build_strengths_and_improvements(
        self, story: list[Any], evaluation_data: dict[str, Any], styles: Any
    ) -> None:
        verdict_eval = evaluation_data.get("verdict_evaluation")
        verdict_str = verdict_eval.get("verdict", "PASS") if verdict_eval else "PASS"

        strengths_html = self._extract_strengths(evaluation_data)
        improvements_html = self._extract_improvements(evaluation_data, verdict_str)

        box_data = [
            [
                Paragraph("<b>3. Key Strengths</b>", styles["SectionHeading"]),
                Paragraph("<b>4. Improvement Areas</b>", styles["SectionHeading"]),
            ],
            [
                Paragraph(strengths_html, styles["BodyTextLight"]),
                Paragraph(improvements_html, styles["BodyTextLight"]),
            ],
        ]

        grid_table = Table(box_data, colWidths=[265, 265])
        grid_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#E2E8F0")),
                ("PADDING", (0, 0), (-1, -1), 7),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(grid_table)
        story.append(Spacer(1, 8))

    def _format_agent_row(
        self, title: str, eval_data: dict[str, Any] | None, default_msg: str, is_hallucination: bool = False
    ) -> list[Any] | None:
        if not eval_data:
            return None

        if is_hallucination and eval_data.get("status") == "INSUFFICIENT_EVIDENCE":
            return [
                Paragraph(f"<b>{title}</b>", ParagraphStyle("TCB", fontName="Helvetica-Bold", fontSize=8.5, textColor=colors.HexColor("#0F172A"))),
                Paragraph("<font color='#64748B'><b>Not Evaluated</b></font>", ParagraphStyle("TCS", fontName="Helvetica-Bold", fontSize=8, textColor=colors.HexColor("#64748B"))),
                Paragraph("Excluded due to insufficient reference evidence.", ParagraphStyle("TCM", fontName="Helvetica-Oblique", fontSize=8.5, textColor=colors.HexColor("#64748B"))),
            ]

        reason = eval_data.get("reasoning", "")
        first_sentence = reason.split(".")[0].strip() + "." if reason else default_msg
        status_tag = "<font color='#15803D'><b>Excellent</b></font>"

        return [
            Paragraph(f"<b>{title}</b>", ParagraphStyle("TCB", fontName="Helvetica-Bold", fontSize=8.5, textColor=colors.HexColor("#0F172A"))),
            Paragraph(status_tag, ParagraphStyle("TCS", fontName="Helvetica", fontSize=8, textColor=colors.HexColor("#15803D"))),
            Paragraph(first_sentence, ParagraphStyle("TC", fontName="Helvetica", fontSize=8.5, textColor=colors.HexColor("#0F172A"))),
        ]

    def _build_agent_summary(
        self, story: list[Any], evaluation_data: dict[str, Any], styles: Any
    ) -> None:
        story.append(Paragraph("5. Multi-Agent Executive Summary", styles["SectionHeading"]))

        rel_row = self._format_agent_row("🎯 Relevance", evaluation_data.get("relevance_evaluation"), "Fully addressed user request.")
        acc_row = self._format_agent_row("✅ Accuracy", evaluation_data.get("accuracy_evaluation"), "All factual claims are correct.")
        hal_row = self._format_agent_row("🛡 Hallucination", evaluation_data.get("hallucination_evaluation"), "No unsupported claims detected.", is_hallucination=True)
        comp_row = self._format_agent_row("📋 Completeness", evaluation_data.get("completeness_evaluation"), "All requested aspects were covered.")

        agent_rows = [row for row in [rel_row, acc_row, hal_row, comp_row] if row is not None]

        summary_table = Table(agent_rows, colWidths=[140, 80, 320])
        summary_table.setStyle(
            TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(summary_table)
        story.append(Spacer(1, 8))

    def _build_conclusion(
        self,
        story: list[Any],
        evaluation_data: dict[str, Any],
        styles: Any,
    ) -> None:
        verdict_eval = evaluation_data.get("verdict_evaluation")
        verdict_str = verdict_eval.get("verdict", "PASS") if verdict_eval else "PASS"

        recommendation = self._get_recommendation(verdict_str)

        rec_paragraph = Paragraph(
            f"<b>6. Executive Recommendation</b><br/>{recommendation}",
            styles["BodyTextLight"],
        )

        footer_box = Table([[rec_paragraph]], colWidths=[540])
        footer_box.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#E2E8F0")),
                ("PADDING", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(KeepTogether(footer_box))

    def _get_star_rating(self, score: float) -> str:
        rounded = round(score)
        full_stars = min(5, max(1, rounded))
        return "★" * full_stars + "☆" * (5 - full_stars)

    def _get_badge_colors(self, verdict: str) -> tuple[str, str, str]:
        if verdict == "PASS":
            return "#DCFCE7", "#15803D", "#86EFAC"
        if verdict == "NEEDS_IMPROVEMENT":
            return "#FEF3C7", "#B45309", "#FDE68A"
        return "#FEE2E2", "#B91C1C", "#FCA5A5"

    def _get_relevance_badge(self, score: int) -> str:
        if score >= 4:
            return "<font color='#15803D'><b>● Highly Relevant</b></font>"
        if score == 3:
            return "<font color='#B45309'><b>● Partially Relevant</b></font>"
        return "<font color='#B91C1C'><b>● Irrelevant</b></font>"

    def _get_accuracy_badge(self, score: int) -> str:
        if score >= 4:
            return "<font color='#15803D'><b>● Highly Accurate</b></font>"
        if score == 3:
            return "<font color='#B45309'><b>● Partially Accurate</b></font>"
        return "<font color='#B91C1C'><b>● Inaccurate</b></font>"

    def _get_hallucination_badge(self, score: int) -> str:
        if score >= 4:
            return "<font color='#15803D'><b>● Fully Grounded</b></font>"
        if score == 3:
            return "<font color='#B45309'><b>● Partially Grounded</b></font>"
        return "<font color='#B91C1C'><b>● Highly Hallucinated</b></font>"

    def _get_completeness_badge(self, score: int) -> str:
        if score >= 4:
            return "<font color='#15803D'><b>● Complete Coverage</b></font>"
        if score == 3:
            return "<font color='#B45309'><b>● Partially Complete</b></font>"
        return "<font color='#B91C1C'><b>● Incomplete</b></font>"

    def _get_recommendation(self, verdict: str) -> str:
        if verdict == "PASS":
            return (
                "The evaluated AI response demonstrates excellent quality across all assessment dimensions. "
                "It is suitable for production deployment, academic submissions, research reports, and client delivery."
            )
        if verdict == "NEEDS_IMPROVEMENT":
            return (
                "The evaluated AI response is acceptable but demonstrates minor gaps in completeness or accuracy. "
                "Review the agent feedback and revise the prompt before production deployment."
            )
        return (
            "The evaluated AI response failed critical quality evaluation thresholds. "
            "Re-evaluating the prompt, context grounding, and reference rules is strongly recommended."
        )
